### ISSUE TITLE
Support for k8s 1.25

### ISSUE THREAD

**Issue by DerrickMartinez** [opencost/opencost#1440] opened 2022-10-20 23:56 UTC
Opencost is broken in k8s 1.25. Need to move from v2beta1 to v2

```
The Beta API version (autoscaling/v2beta1) of HorizontalPodAutoscaler is no longer served as of version 1.25. This API was deprecated in version 1.23. Migrate manifests and API clients to use the autoscaling/v2 HorizontalPodAutoscaler API version.
```

**Comment by dwbrown2** [comment] 2022-10-21 00:54
Thanks for reporting, @DerrickMartinez! Can you share what install path you're using?

**Comment by DerrickMartinez** [comment] 2022-10-21 06:47
Not sure what you mean, but it’s the latest version on quay. (1.97)

To get it working, an update is needed for the autoscaling hpa references to v2beta1 should be v2

**Comment by ruudvanderweijde** [comment] 2022-10-21 11:54
I can confirm that Opencost stopped working on Kubernetes 1.25

**Comment by AjayTripathy** [comment] 2022-10-24 03:01
Here are the references to autoscaler: https://github.com/opencost/opencost/search?q=autoscaling%2Fv2beta1

I believe the k8s client-go library may need to be updated to get this into autoscaling v2.

@michaelmdresser did this last: https://github.com/opencost/opencost/commit/c20b870ce47fc552bfd2de1c3ea0a4523eae7cc4 , can you help out with the upgrade here?

**Comment by michaelmdresser** [comment] 2022-10-25 14:13
Have a partially-complete/partially-tested PR open to attempt to address this: https://github.com/opencost/opencost/pull/1447. Still working on testing/validation and checking official K8s docs to figure out API version compatibility for older versions of K8s. Just wanted to give y'all an update on the progress so far!

**Comment by michaelmdresser** [comment] 2022-10-25 19:45
Thoughts so far after some research. Posting here for common reference so I can start some conversations internally.

## Why this is broken
As can be seen in the first-attempt PR (https://github.com/opencost/opencost/pull/1447/files#diff-fecaca093692f3443309a9205d4bc3afef0e3207ae9174528181dde143bfa533) the cluster cache code expects HPAs to specifically be `autoscaling/v2beta1` HPAs. This is not a stable API and appears to be removed in K8s v1.25 (this issue exists, after all 🙂).

## History of HPA API (`autoscaling/vX`)
I did some research in the K8s [CHANGELOG](https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG) and constructed this (condensed) history of HPA (`autoscaling/`) API versioning:
- K8s 1.2: autoscaling/v1 HPA is GA
- K8s 1.6: extensions/v1beta1 HPA removed, suggested to use autoscaling/v1. autoscaling/v2alpha1 exists
- K8s 1.8: autoscaling/v2alpha1 -> autoscaling/v2beta1
- K8s 1.9: autoscaling/v2beta1 enabled by default
- K8s 1.12: autoscaling/v2beta2 introduced
- K8s 1.19: autoscaling/v2beta1 deprecated for v2beta2
- K8s 1.23: autoscaling/v2 HPA GA, autoscaling/v2beta2 deprecated

## Options to fix
I see a few options forward at the moment.
1. Switch our autoscaling/v2beta1 import to autoscaling/v2beta2. v2beta2 was introduced in K8s 1.12. v2beta2 was deprecated in v1.23 but I think should still exist in v1.25. This requires no branching code but does make our minimum-supported version K8s 1.12.
2. Remove HPA support from clustercache. We don’t appear to use the HPA support anywhere in the code. This basically solves the problem for free. I am not sure why HPA currently exists in clustercache -- I have an open thread.
3. Switch clustercache HPA support from autoscaling/v2beta1 to autoscaling/v1. This requires no branching code and is supported all the way back to K8s v1.2. However, we lose the ability to access autoscaling/v2 HPA data which, as noted, isn't used anywhere anyway. Relying on stable APIs is _good_.
4. Do 3, but also add a branching code path for autoscaling/v2 HPAs, if available in the cluster.

In order, I like options 3 > 2 > 4 > 1.

2 is easiest, as long as we don't have a reason to keep the HPA part of clustercache around.

## Commentary
In the future, I think we should be wary of building in “forced” support for vXalphaY and vXbetaY APIs into our code. In an ideal world we would optionally support such things (see e.g. PV right-sizing, where [metric can be unavailable and the whole application doesn’t break](https://github.com/opencost/opencost/pull/1438)) but we don’t have that for clustercache right now because of the current interface design.

**Comment by michaelmdresser** [comment] 2022-10-26 15:53
We have an open PR, using option 2, which should provide K8s v1.25 support once merged.

**Comment by michaelmdresser** [comment] 2022-10-26 15:53
https://github.com/opencost/opencost/pull/1452

**Closed as completed** 2022-10-26 16:11 UTC
Labels: P0, v1.98

**Comment by nickolashkraus** [comment] 2022-12-20 17:20
This change has not yet made it into the quay.io/kubecost1/kubecost-cost-model:latest image. OpenCost still needs to be run on Kubernetes <1.25.

**Comment by AjayTripathy** [comment] 2022-12-20 21:58
@nickolashkraus sorry about that... could you try the image tag 
`quay.io/kubecost1/kubecost-cost-model:prod-1.99.0`
 instead?

**Comment by nickolaskraus-wf** [comment] 2022-12-20 22:08
Yep, I have prod-1.99.0 pinned. Just thought I'd let you all know, since the OpenCost K8s manifest still uses latest:
* https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml

```yaml
- image: quay.io/kubecost1/kubecost-cost-model:latest
```

**Comment by AjayTripathy** [comment] 2022-12-20 22:09
Thank you for the report! We'll get it fixed!
