### ISSUE TITLE
Support multiple currencies

### ISSUE THREAD

**Issue by powdermouse** [opencost/opencost#1688] opened 2023-02-14 06:05 UTC
Hi, how to change currency display from $ to EUR in opencost?

**Comment by thomasvn** [comment] 2023-02-14 21:30
@nealormsbee Do you know if the `currency` value originates from the frontend or backend? Where can it be set?

**Comment by nealormsbee** [comment] 2023-02-15 00:38
I pulled up the source code and it appears that, as of now, the currency in OpenCost cannot be adjusted =/
We just set it to USD and there's no way to change it:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/981904/218895235-b0f14318-441a-4662-9c57-045c3c5492d4.png">

**Comment by brot** [comment] 2023-03-27 08:16
Why is this just a "question" and not a "bug" or "feature request"? 
A modern software in the year 2023 should be able to deal with more than one currency. Are there any plans to fix the hard-coded USD currency and make this customizable?

**Comment by dwbrown2** [comment] 2023-03-27 17:02
@brot it started as a question but I agree that it should be a feature request given that it is the year 2023!

**Comment by AjayTripathy** [comment] 2023-03-27 17:04
Hey @brot , happy to take a PR to get this in the opencost frontend. 

We do support currency changes in the kubecost frontend, if you'd like to check that out!

**Comment by mattray** [comment] 2023-03-28 02:49
https://github.com/opencost/opencost/issues/1800 is a duplicate of this, but this one has a little more context so we can leave them both open for now.

**Comment by saif-xgrid** [comment] 2023-03-28 15:33
@mattray Please assign this issue to me.hopefully It will be my first useful contribution

**Comment by saif-xgrid** [comment] 2023-04-06 21:59
Hi @mattray @AjayTripathy . I have looked into this issue and the solution I came up with is that we have to integrate the third-party library for the exchangerates. The one I am planning to use is [this](https://app.exchangerate-api.com/). One more thing we can do is to add the dropdown of supported currencies above in the dashboard similar like the `Data Range` and `Breakdown` . For generating the API key, I will be using my own personal email. Is it good to go or I have to follow some other approach. I have tried changing the hard-coded string in the image but its only changing the symbol of the currency but not the actual value of currency. just changing it means 1$=1£ so according to me we have to handle this through live currency exchange rates.
![image](https://user-images.githubusercontent.com/121641394/230501301-668ef9e6-f1c9-4601-af06-bbbfdb82e09f.png)

**Comment by mattray** [comment] 2023-04-06 22:45
I don't think we need to support exchange rates. My understanding is that the billing amount returned by APIs is in the local currency and we just need to put the right currency indicator in front of it based off the locale. Something along the lines of 

USD: `$`
EUR: `€`
CNY: `¥`
etc.

and I would expect that to be already supported by whatever we're calling with `useState('USD')`

@AjayTripathy am I correct?

**Comment by AjayTripathy** [comment] 2023-04-10 19:08
Yes-- the currency should be in whatever code your API returns so it's just display that needs to change. I don't think we want to add a full currency exchange library, especially since we don't exactly want new dependencies on network access.

**Comment by saif-xgrid** [comment] 2023-05-14 09:55
HI @mattray, I have done this, is this okay or do we need to know to do some thing other than this 
![image](https://github.com/opencost/opencost/assets/121641394/13929dc6-40f0-4a23-80d4-a549a3531927)
![image](https://github.com/opencost/opencost/assets/121641394/e86bd98c-daf7-4c02-a9c7-a33443b0f2d5)
![image](https://github.com/opencost/opencost/assets/121641394/2a883d29-e755-4a29-ae89-784dc877cced)

Are these changes enough? should I make the PR ?

**Comment by mattray** [comment] 2023-05-15 09:57
Interesting, does that persist between sessions?

**Comment by saif-xgrid** [comment] 2023-05-15 17:09
Yes, it is

**Comment by mattray** [comment] 2023-05-15 23:48
I'm happy to merge this. @AjayTripathy @dwbrown2 does this work for you or did you want something locale/env variable derived?

**Comment by nealormsbee** [comment] 2023-05-16 15:17
That screenshot looks good to me, for what it's worth.

**Comment by mattray** [comment] 2023-05-18 07:01
@saif-xgrid could you make a PR for us to review?

**Comment by saif-xgrid** [comment] 2023-05-22 21:26
Hey @mattray  here is the PR of this : https://github.com/opencost/opencost/pull/1940

**Closed as completed** 2023-06-02 00:28 UTC
Labels: enhancement, good first issue, opencost
