### ISSUE TITLE
Compare on-prem price with AWS or any

### ISSUE THREAD

**Issue by mohang6770** [opencost/opencost#1806] opened 2023-03-24 16:08 UTC
Hi Team,

I am a frequent user of your platform and find it very helpful in tracking the costs of our on-premises infrastructure. However, I think it would be incredibly valuable if OpenCost could also provide a feature to compare the costs of on-premises infrastructure with those of cloud services, specifically with AWS.

As more and more companies are migrating to the cloud, it's becoming increasingly important to have a clear understanding of the costs and benefits of on-premises versus cloud infrastructure. Having a feature that could compare these costs side by side would be a huge asset for us and other businesses in similar situations.

Ideally, this feature would allow us to input our on-premises costs, including hardware, maintenance, and personnel, and then generate a report that shows the equivalent costs for a similar setup on AWS. The report could also include estimates for data transfer, storage, and other relevant factors.

I believe that this feature would not only make OpenCost an even more valuable tool, but it would also help businesses make more informed decisions about their infrastructure choices.

Thanks

**Comment by mattray** [comment] 2023-03-25 00:22
@mohang6770 I agree that this would be a very useful feature

Kubecost released `kubectl cost predict` recently and it would make sense to be eventually able to compare on-prem vs. cloud (or cloud #1 vs. cloud #2) pricing.
https://blog.kubecost.com/blog/kubecost-version-1-100-2-new-feature-highlights/#ability-to-predict-cost-before-deployment-with-kubectl-cost-predict

I'm closing this issue as a duplicate of https://github.com/opencost/opencost/issues/1441 and https://github.com/opencost/opencost/issues/1711

**Comment by mattray** [comment] 2023-03-25 00:23
Not completed, duplicate.

**Closed as not planned** 2023-03-25 00:23 UTC
Labels: enhancement, opencost
