### ISSUE TITLE
Spot recommendation page is broken

### ISSUE THREAD

**Issue by DanTulovsky** [opencost/opencost#1167] opened 2022-04-19 15:35 UTC
Clicking on `Check out the new Kubecost Spot readiness guide` takes me to the page, which briefly shows a loading status, and then goes entirely blank.  The console has the following in it:

<img width="1759" alt="Screen Shot 2022-04-19 at 11 35 03 AM" src="https://user-images.githubusercontent.com/509887/164041396-2386fc75-88d5-44b8-a3a6-296267c66f59.png">

gz#1682

**Comment by kbrwn** [comment] 2022-04-19 15:38
@DanTulovsky It seems you need a lot of help and that your kubecost install is not stable. Could you join our [slack](https://github.com/kubecost) so we can work together there instead of through multiple github issues?

**Comment by kbrwn** [comment] 2022-04-19 15:42
Sorry wrong link to slack there: https://join.slack.com/t/kubecost/shared_invite/enQtNTA2MjQ1NDUyODE5LWFjYzIzNWE4MDkzMmUyZGU4NjkwMzMyMjIyM2E0NGNmYjExZjBiNjk1YzY5ZDI0ZTNhZDg4NjlkMGRkYzFlZTU

**Comment by DanTulovsky** [comment] 2022-04-19 15:47
Sure, I figured you'd want an easy way to track this. :)

**Comment by kbrwn** [comment] 2022-04-19 15:50
@DanTulovsky 5 issues is a lot in a such small period and many of these are likely resolvable without code changes. We try to qualify if an issue is specific to a cluster or kubecost deployment and get data like bug report from /setting.html and profile/heap.

**Comment by AjayTripathy** [comment] 2022-04-19 16:36
@DanTulovsky , love the enthusiasm and thank you for the issues! There's probably some sort of root cause of all of these we're missing without more insight into your cluster setup and slack would be best to figure it out since we may need private data about your cluster setup.

**Comment by DanTulovsky** [comment] 2022-04-19 17:42
I think this is an actual bug though.  At least it's still broken with the increased ingress timeout. It fails within a few seconds of going to the page.

**Comment by AjayTripathy** [comment] 2022-04-20 14:00
Thanks @DanTulovsky . We haven't been able to repro but will get this triaged and looked at.

**Comment by DanTulovsky** [comment] 2022-04-20 14:53
The error seems to be from this request:

Request URL: https://kubecost.public.lightstep.io/model/savings/spotChecklistClusterSizing?minOnDemandNodeCount=2&minSpotNodeCount=3&targetUtilization=0.9&allowSharedCore=true&window=1d

which returns a 503 with: error creating spot-ready workload
distributions: failed to create any WorkloadDistributions for
AllocationSetRange

**Comment by dwbrown2** [comment] 2022-04-20 14:56
@michaelmdresser is likely the most familiar here

**Comment by michaelmdresser** [comment] 2022-04-20 16:37
Hi @DanTulovsky, thanks for the clear report! This is a bug in our frontend error handling. We'll get to work on a fix.

**Comment by michaelmdresser** [comment] 2022-04-25 17:33
We've merged a change that will prevent the UI from fully crashing, it will be part of the next release.

There's still an outstanding problem with the `/spotChecklistClusterSizing` API: we shouldn't be getting a 500. I've been able to reproduce this in dev environments with the latest code. @dwbrown2 / @AdamStack18 I don't have bandwidth this week, just wanted to raise visibility that there's something else happening here.

**Comment by dwbrown2** [comment] 2022-04-25 22:20
@michaelmdresser what's the cause of the 500? Should we have someone else run with this if you can't fix for this release?

**Comment by michaelmdresser** [comment] 2022-04-26 13:45
I don't know the cause. If there's time next week, I might be able to pick this up, otherwise someone else will have to take it (I'm always happy to provide support here).

**Closed as completed** 2022-05-06 14:58 UTC
Labels: bug, next release

**Comment by michaelmdresser** [comment] 2022-05-09 12:06
Hi @DanTulovsky, this issue should be resolved in our upcoming release!
