### ISSUE TITLE
High memory usage after update on v1.91.0

### ISSUE THREAD

**Issue by dschunack** [opencost/opencost#1108] opened 2022-03-11 15:02 UTC
Hi,

we updated today kubecost to use the latest release v1.91.0 and the kubecost-cost-analyzer POD crashed duo to an OOM.
The costs-model Container used a lot of memory, means GB's of memory. We saw today spikes up to 120GB of Memory.
I think this is not normal. The v1.90.1 costs-model used 100-200MB. We switched back to v1.90.1

v1.91.0
![Xnip2022-03-11_15-57-11](https://user-images.githubusercontent.com/19306599/157892424-97be690d-f41b-4342-8be0-5d4b0e7ca3c5.jpg)

v1.90.1
![Xnip2022-03-11_15-57-48](https://user-images.githubusercontent.com/19306599/157892453-8d622fe7-4195-4139-bc25-944b290b40d2.jpg)

gz#1499

**Comment by kbrwn** [comment] 2022-03-11 18:00
hi @dschunack did you happen to look at the logs during this time of high resource usage? Anything stand out? If you have a dev cluster where you can replicate this issue a heap/profile during high usage would help with further debugging: [Kubecost Memory Usage](https://guide.kubecost.com/hc/en-us/articles/4407595921431)

**Comment by dschunack** [comment] 2022-03-11 18:56
Hi @kbrwn ,

I found a running kubecost that consumed only 3GB, the most crashes in seconds. 
Logs are attached and also the profile/heap.

Hope it helps.

[cost-model.log](https://github.com/kubecost/cost-model/files/8234628/cost-model.log)
[profile.log](https://github.com/kubecost/cost-model/files/8234640/profile.log)
[heap.log](https://github.com/kubecost/cost-model/files/8234643/heap.log)

**Comment by AjayTripathy** [comment] 2022-03-11 19:13
Hi @dschunack unfortunately that heap seems reasonable (within a few Gi) and isn't that helpful. If we can't get a heap because the pod is crashing too quickly, any way we could get a log from a 1.91.0 instance that crashes? You can use "--previous" to pull data from a crashing or terminating pod.

**Comment by AjayTripathy** [comment] 2022-03-11 20:16
I also think a bug report, plus node, cluster, and storage class architecture would be really useful here, seeing as we can't reproduce this in any of our test clusters.

**Comment by michaelmdresser** [comment] 2022-03-11 20:41
@dschunack, the most important thing that would help us is the logs of the `kubecost-cost-analyzer` pod running `v1.91.0` that OOMs. As Ajay has mentioned, you can use `--previous` if it was the last instance of the pod that crashed, e.g.:

```bash
kubectl logs \
    --namespace kubecost \
    -l app=cost-analyzer \
    -c cost-model \
    --tail=-1 \
    --previous
```

If you get an error like:
```
Error from server (BadRequest): previous terminated container "cost-model" in pod "kubecost-cost-analyzer-XXXXX" not found
```

You may need to specify the _exact_ pod that OOMs, rather than using `--previous`, like so:

```bash
kubectl logs \
    --namespace kubecost \
    -c cost-model \
    --tail=-1 \
    "kubecost-cost-analyzer-65b598c65c-z2ghm" # replace with the crashed Pod's name
```

**Comment by dschunack** [comment] 2022-03-11 21:06
Hi,

here are the information's. 

We use EKS 1.21 and the Node is a r5a.2xlarge x86_64. 
Storage Class is EBS GP3
docker 20.10.7
kernel: 5.4.176-91.338.amzn2.x86_64
k8s: v1.21.5-eks-9017834

`
kubectl -n kubecost get pvc
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                       AGE
kubecost-cost-analyzer   Bound    pvc-a709bb37-871a-4bc6-84a1-0525692989b2   1Gi        RWO            linux-ext4-gp3-ebs-csi-encrypted   259d`

`
kubectl -n kubecost get pods 
NAME                                     READY   STATUS             RESTARTS   AGE
kubecost-cost-analyzer-bd7c7f4d4-94czx   2/3     CrashLoopBackOff   6          13m`

I run the logs command two times.

[messages.log](https://github.com/kubecost/cost-model/files/8235739/messages.log)
[cost-model-new.log](https://github.com/kubecost/cost-model/files/8235751/cost-model-new.log)
[cost-model-new2.log](https://github.com/kubecost/cost-model/files/8235753/cost-model-new2.log)
[kubecost-describe.log](https://github.com/kubecost/cost-model/files/8235767/kubecost-describe.log)

[sc.yaml.log](https://github.com/kubecost/cost-model/files/8235748/sc.yaml.log)

**Comment by AjayTripathy** [comment] 2022-03-11 23:06
Hi @dschunack it looks like your pod is dying in the middle of loading your cache. It seems fairly unlikely that this is actually dying while holding 120Gi of memory-- is it possible that your memory accounting above is summating terminating pods?

Regardless, I think we want to get one pod stable, can we try to lower our cache size to just a few days to see memory usage? You can set
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L278

to something like 3 and my guess is the pod will come up.

**Comment by dschunack** [comment] 2022-03-15 14:47
Hi @AjayTripathy,

It's the real memory usage of the costs-model container and on r5a.4xlarge instance it used a large amount of memory.
I will change it in our dev environment to check if it helped to reduce the etl. I will inform you soon

**Comment by kbrwn** [comment] 2022-03-15 17:16
Hi @dschunack you might wish to upgrade to the latest kubecost release which fixes a performance regression: https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.91.1

**Comment by dschunack** [comment] 2022-03-15 18:01
Hi @kbrwn , I will test the new release tomorrow. Thanks for the Info.

**Comment by dschunack** [comment] 2022-03-16 19:17
Hi @kbrwn ,

I tested it today with the latest release v1.91.2, but it still consumed a lot of memory and crashed.
It's running on one of our EKS and the costs-model consumed between 1.4 to 1.8Gi memory, but it's running.

```sh
kubectl -n kubecost top pod kubecost-cost-analyzer-5ff94ff94d-699cn
NAME                                      CPU(cores)   MEMORY(bytes)   
kubecost-cost-analyzer-5ff94ff94d-699cn   122m         1866Mi
```

![Xnip2022-03-16_20-02-30](https://user-images.githubusercontent.com/19306599/158667235-29993cf3-f803-458c-ae16-9bd218216b32.jpg)

If we check now the data in the kubecost dashboard it looks very strange and tells us, we spend 180k€ per day and this is not correct. Looks like a problem with the disks calculation and also some data of the last days are no longer shown.
We saw also a lot of PVC warning messages in the costs-model logs.

![Xnip2022-03-16_20-05-14](https://user-images.githubusercontent.com/19306599/158667703-09f78f05-c1db-49f3-8a7f-3a8da2ca2365.jpg)

On another EKS is kubecost no longer running. We removed it today completely (Deployment/PVC/Namespace), but after a new fresh installation the POD comes not up. The costs-model Container crashed duo to an OOM and we see a lot of PVC Warning messages.

Looks like this:

```sh
I0316 19:09:44.806562       1 log.go:32] [Warning] Asset ETL: disk 'pvc-301e2c06-7259-43bf-894a-0f0db435faea' end outside window: 2022-03-16T19:01:00 not in [2022-03-16T18:00:00, 2022-03-16T19:00:00]
I0316 19:09:44.806571       1 log.go:32] [Warning] Asset ETL: disk 'pvc-300b91cc-53b8-437e-af4b-02ddeb18d6b5' end outside window: 2022-03-16T19:01:00 not in [2022-03-16T18:00:00, 2022-03-16T19:00:00]
I0316 19:09:44.806580       1 log.go:32] [Warning] Asset ETL: disk 'pvc-c54a6a4b-363c-4304-8899-092d75254312' end outside window: 2022-03-16T19:01:00 not in [2022-03-16T18:00:00, 2022-03-16T19:00:00]
I0316 19:09:44.806589       1 log.go:32] [Warning] Asset ETL: disk 'pvc-584ae54a-279c-45c0-b4a0-c812386c51fd' end outside window: 2022-03-16T19:01:00 not in [2022-03-16T18:00:00, 2022-03-16T19:00:00]
I0316 19:09:44.806598       1 log.go:32] [Warning] Asset ETL: disk 'pvc-d4297520-680c-4b3c-ac73-16acee577ebe' end outside window: 2022-03-16T19:01:00 not in [2022-03-16T18:00:00, 2022-03-16T19:00:00]
I0316 19:09:44.806615       1 log.go:32] [Warning] Asset ETL: disk 'pvc-f70928a4-8775-4250-bdc7-3123f06f1747' end outside window: 2022-03-16T19:01:00 not in [2022-03-16T18:00:00, 2022-03-16T19:00:00]
I0316 19:10:36.085693       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085724       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085728       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085733       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085740       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085745       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085752       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085756       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085760       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085764       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085771       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085775       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085780       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085783       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085787       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085792       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085798       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085804       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085808       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085812       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085817       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085833       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085838       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085842       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085859       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085867       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085870       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085879       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085893       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085898       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085903       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085907       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
I0316 19:10:36.085911       1 log.go:32] [Warning] CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
```

We postponed the Update for the moment.

**Comment by kbrwn** [comment] 2022-03-16 19:24
hi @dschunack do you see results in prometheus when querying for `kube_persistentvolume_capacity_bytes`?

**Comment by dschunack** [comment] 2022-03-16 19:33
Hi @kbrwn ,

yes, we see a lot of results and Prometheus is working fine. ~5400 for the last 6h.

![Xnip2022-03-16_20-31-50](https://user-images.githubusercontent.com/19306599/158675137-d48d99b6-2293-433c-aecd-1312c4e0f85e.jpg)

**Comment by dschunack** [comment] 2022-03-17 07:52
Current memory usage of the go process in the cost-model container.

```sh
Mem: 12273012K used, 3931900K free, 1892K shrd, 37396K buff, 7457160K cached
CPU:  18% usr   6% sys   0% nic  75% idle   0% io   0% irq   0% sirq
Load average: 2.80 1.92 1.45 12/919 26
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 1001     R    4186m  25%   7  10% /go/bin/app
   19     0 1001     S     1696   0%   2   0% sh
   26    19 1001     R     1624   0%   2   0% top
```

**Comment by mbolt35** [comment] 2022-03-17 16:24
@dschunack I'm confused about how you are measuring this. Your first image has `WSS` in the heading (your comparator). I'm not even sure how you're measuring WSS on a *nix kernel, can you shed some light there? 

VSZ memory is also not necessarily indicative of the overall physical RAM usage by the application. While RSS isn't perfect, it's probably closer to actual physical memory usage. One suggestion I have is to install metrics-server (if it's not already installed) on your cluster such that you can use `kubectl top pod -n kubecost`, which can show you what memory and CPU look like from Kubernetes perspective (likely the most relevant in this case since Kubernetes is OOM killing). 

Also, if you have a version of cost-model with high memory usage that is stable, if you could send us a heap (via `http://<your-kubecost-endpoint>/model/debug/pprof/heap`) of that specific running instance, that would be helpful for us. 

Thank you!

**Comment by dschunack** [comment] 2022-03-17 16:57
Hi @mbolt35 ,

The first Picture was the memory usage with version v1.91.0 and now with the latest v1.91.2.
With the latest release is the memory usage quite better, but not good.

The [memory output](https://github.com/kubecost/cost-model/issues/1108#issuecomment-1070485927) comes directly from top in the cost-model container.

We use Prometheus and the NodeExporter on the Nodes to get metrics of the containers on the Nodes, also the metrics server is also installed. Both collect the same metrics on the Node for Containers and.....

I already added the output of top pods yesterday and it's exactly the same as Prometheus shows. [See comment](https://github.com/kubecost/cost-model/issues/1108#issuecomment-1069521984)

> I tested it today with the latest release v1.91.2, but it still consumed a lot of memory and crashed. It's running on one of our EKS and the costs-model consumed between 1.4 to 1.8Gi memory, but it's running.
> 
> ```shell
> kubectl -n kubecost top pod kubecost-cost-analyzer-5ff94ff94d-699cn
> NAME                                      CPU(cores)   MEMORY(bytes)   
> kubecost-cost-analyzer-5ff94ff94d-699cn   122m         1866Mi
> ```

New heap as attachment.
[heap.v1.91.2.log](https://github.com/kubecost/cost-model/files/8288293/heap.v1.91.2.log)

**Comment by mbolt35** [comment] 2022-03-17 18:09
@dschunack The heap you posted lines up fairly closely to the `1866Mi` from kubectl top. The go runtime appears to have freed `500mb` that the kernel has yet to reclaim. 
```
Showing nodes accounting for 1217.86MB, 93.20% of 1306.66MB total
```
Nothing in that heap looks suspiciously high, and it appears to be running as expected from our side. 

What I would like to understand is the first image you posted which shows `cost-model` running at `99MiB` compared to what looks like `cost-model` running at `120GiB`. Is this for a single pod, many pods? I noted that the graph you posted shows Working Set Size memory (WSS as it's labeled in the bottom most image - I've circled in the image below), and there's not a clear indication of what the top graph is measuring. *Nix operating systems usually report VSZ, RSS, and sometimes PSS, so the WSS measurement surprised me, and I was just curious as to how that was being measured. It doesn't seem possible for our pod to run between 100-200MiB given the heap that was reported. 

![image](https://user-images.githubusercontent.com/334480/158860502-cab32b61-1244-4ce5-b09b-2dd3fc223c18.png)

Cost-Model in an idle state will likely run at a more reduced size, however, the heap reveals actively running requests, which can definitely cause the memory to expand while it services those requests.  We'll discuss this heap profile internally and see if anyone spots anything unusual.

**Comment by dschunack** [comment] 2022-03-21 14:50
HI @mbolt35 

> What I would like to understand is the first image you posted which shows cost-model running at 99MiB compared to what looks like cost-model running at 120GiB. Is this for a single pod, many pods? 

It's a single POD and only the cost-model container was selected in grafana. After the Update on v1.91.0 the memory grows and grows without stopping and reached the Node limit.

>I noted that the graph you posted shows Working Set Size memory (WSS as it's labeled in the bottom most image - I've circled in the image below), and there's not a clear indication of what the top graph is measuring. *Nix operating systems usually report VSZ, RSS, and sometimes PSS, so the WSS measurement surprised me, and I was just curious as to how that was being measured. It doesn't seem possible for our pod to run between 100-200MiB given the heap that was reported.

At the moment we monitor with prometheus/grafana only the WSS Memory usage and not the RSS. 
WSS is also used for kubectl top pod memory output. Both Pictures shows the WSS Memory usage of the cost-model Container of the kubecost-analyzer POD.
The Reported heap is from the latest kubecosts version. If you need also a heap of an older kubecost version, please let me know. We can deploy a second kubecost with a older version.

**Comment by AjayTripathy** [comment] 2022-03-24 02:08
Hi @dschunack we've identified a few performance regressions that will be fixed in an upcoming release but a heap of an older version would be great as well.

**Comment by kbrwn** [comment] 2022-03-30 18:51
hi @dschunack A new RC is available: https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.92.0-rc.0

It would be great to compare performance with this rc vs the current release in your environment if possible. You can append `--devel` cmd to `helm upgrade` to install the latest rc.

**Comment by dschunack** [comment] 2022-03-31 14:38
Hi @kbrwn ,

Thanks for the Update and we will try it out. The link is not working, but i think you mean release v1.92.0-rc.0.

**Comment by kbrwn** [comment] 2022-03-31 16:33
@dschunack Sorry I guess the release wasn't public quite yet! I updated the link.

**Comment by dschunack** [comment] 2022-04-01 08:57
Hi @kbrwn ,

We updated one of our kubecost to RC0 and the Memory usage is 50% less then before, but not as good as before.
Working memory (WSS) goes down from 4Gi to 2Gi for the cost model container.

I wanted to deploy a second kubecost on the same EKS but in a different namespace to deliver the heap/profile of a different version.
However, I noticed that some templates are not ready to roll out multiple kubecost for testing on the same k8s with PSP + NetworkCosts enabled.

I'll do a PR later to fix this.

**Comment by dschunack** [comment] 2022-04-01 10:48
PR created: [#1344](https://github.com/kubecost/cost-analyzer-helm-chart/pull/1344)

**Comment by mattray** [comment] 2023-05-25 06:15
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).

**Closed as completed by mattray** 2023-05-25 06:15 UTC
Labels: next release, kubecost
