### ISSUE TITLE
opencost ui 'npm install' is broken across multiple platforms

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1519] opened 2022-12-02 12:29 UTC
I'm attempting to build the UI in the `develop` branch and I am facing npm failures on multiple targets. I have an M1 Macbook Air (Arm64) with npm installed via Homebrew (8.19.3), so the first attempt at building locally I followed the instructions
```
cd ui
npm install
```

This fails with the following error, the attached logfile has the full details.
```
npm ERR! command sh -c -- node-gyp-build
```
[2022-12-02T12_12_29_380Z-debug-0.log](https://github.com/opencost/opencost/files/10140986/2022-12-02T12_12_29_380Z-debug-0.log)

Next I decided I should use the Dockerfile instead of developing on my laptop. 
```
docker build .
```
also fails in the same command, output: [docker_build.log](https://github.com/opencost/opencost/files/10141024/docker_build.log)

Next I thought it was perhaps an Arm64 issue. ```docker buildx build --platform linux/arm64 .``` produces the same error as ```docker build .```, so I tested building x86 with

```docker buildx build --platform linux/amd64 .```

This actually progressed farther, but now fails in 
```
   7 | >>> RUN npx parcel build src/index.html
```
Output: [docker_buildx_amd64.log](https://github.com/opencost/opencost/files/10141075/docker_buildx_amd64.log)

**Comment by biancaburtoiu** [comment] 2022-12-05 13:54
Hi @mattray! For the local build, I’m not able to reproduce your error - something might be off in your npm install? My current `node -v` returns v12.18.4, could you try to use that same version (I believe it’s `nvm install 12.18.4` then `nvm use 12.18.4`) and see if that helps?

**Comment by biancaburtoiu** [comment] 2022-12-05 18:40
Re: the docker build, I believe this is some M1-related incompatibility (I have the same machine and was able to reproduce). I'll share more updates here but once this image is uploaded on quay.io via the release scripts, it should work as expected

**Comment by mattray** [comment] 2022-12-05 22:33
My npm is 8.19.3 and docker build pulls up 8.19.2. I "fixed" the issue by removing the package-lock.json and letting it regenerate, but we probably need to standardize a version of npm to something newer.

**Comment by mattray** [comment] 2022-12-05 23:56
FWIW the README says `npm >= 7.0.0`, which probably needs updating

**Comment by nealormsbee** [comment] 2022-12-08 21:07
@mattray I don't have permissions to assign myself this issue. Can you assign it to me and apply the v1.100 label so I don't lose track of it please?

**Closed as completed** 2023-01-04 21:32 UTC
Labels: opencost, v1.100

**Comment by burkeshartsis** [comment] 2023-01-05 15:38
I'd highly encourage using an `.nvmrc` file and updating to a more recent version of Node. The current LTS version is 18. Bonus points if you standardize your node version across all repositories within a github org. I know the `opencost-website` could benefit from this as well.
