### ISSUE TITLE
node_total_hourly_cost inaccurate for some nodes in AWS

### ISSUE THREAD

**Issue by liorfranko** [opencost/opencost#2243] opened 2023-10-26 08:28 UTC
**Describe the bug**
We're running opencost with default configurations, without customPricing, without CUR integration, and without spot-data-feed.
We need the prices based on AWS public prices.

I noticed that the metric node_total_hourly_cost is inaccurate for some nodes.
I compared two c5d.18xlarge nodes in zone us-east-1e in Virginia.
<img width="937" alt="Screen Shot 2023-10-26 at 11 31 04" src="https://github.com/opencost/opencost/assets/20726865/7b3125ee-47f6-4684-87a0-eafd04eed596">

Inaccurate node:
<img width="1660" alt="Screen Shot 2023-10-26 at 11 18 06" src="https://github.com/opencost/opencost/assets/20726865/a4af38ce-d60a-4029-a77b-ad4b1da35833">
```
kubectl describe nodes ip-10-207-136-27.ec2.internal
Name:               ip-10-207-136-27.ec2.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=c5d.18xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1e
                    intent=apps
                    k8s.io/cloud-provider-aws=7e43c8d478ffdd4cb3168691ff335629
                    karpenter.k8s.aws/instance-category=c
                    karpenter.k8s.aws/instance-cpu=72
                    karpenter.k8s.aws/instance-encryption-in-transit-supported=false
                    karpenter.k8s.aws/instance-family=c5d
                    karpenter.k8s.aws/instance-generation=5
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-local-nvme=1800
                    karpenter.k8s.aws/instance-memory=147456
                    karpenter.k8s.aws/instance-network-bandwidth=25000
                    karpenter.k8s.aws/instance-pods=737
                    karpenter.k8s.aws/instance-size=18xlarge
                    karpenter.sh/capacity-type=spot
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=ds-infra-network-online-spot
                    karpenter.sh/registered=true
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-207-136-27.ec2.internalec2ssa.info
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=c5d.18xlarge
                    nodegroup-name=ds-infra-network-online-spot
                    project=mobile-ds-infra-network-online
                    topology.ebs.csi.aws.com/zone=us-east-1e
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1e
```

Accurate node:
<img width="1659" alt="Screen Shot 2023-10-26 at 11 15 03" src="https://github.com/opencost/opencost/assets/20726865/38473d0c-db81-4eab-b683-b39544eb365d">
```
kubectl describe nodes ip-10-207-128-191.ec2.internal
Name:               ip-10-207-128-191.ec2.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=c5d.18xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1e
                    intent=apps
                    k8s.io/cloud-provider-aws=7e43c8d478ffdd4cb3168691ff335629
                    karpenter.k8s.aws/instance-category=c
                    karpenter.k8s.aws/instance-cpu=72
                    karpenter.k8s.aws/instance-encryption-in-transit-supported=false
                    karpenter.k8s.aws/instance-family=c5d
                    karpenter.k8s.aws/instance-generation=5
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-local-nvme=1800
                    karpenter.k8s.aws/instance-memory=147456
                    karpenter.k8s.aws/instance-network-bandwidth=25000
                    karpenter.k8s.aws/instance-pods=737
                    karpenter.k8s.aws/instance-size=18xlarge
                    karpenter.sh/capacity-type=spot
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=ds-infra-network-online-spot
                    karpenter.sh/registered=true
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-207-128-191.ec2.internalec2ssa.info
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=c5d.18xlarge
                    nodegroup-name=ds-infra-network-online-spot
                    project=mobile-ds-infra-network-online
                    topology.ebs.csi.aws.com/zone=us-east-1e
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1e
```

**To Reproduce**
Querying for node_cpu_hourly_cost < 0.01
<img width="1661" alt="Screen Shot 2023-10-26 at 11 20 46" src="https://github.com/opencost/opencost/assets/20726865/87f06c02-67bc-4f70-9d9f-77b348b9be16">

**Expected behavior**
On AWS, the node_cpu_hourly_cost can't be less than 0.01 (Maybe for T instances, but we don't use them)
All instances with the same type in the same zone should have the same price.

**Which version of OpenCost are you using?**
v1.106.3

**Comment by mattray** [comment] 2023-10-30 07:14
@liorfranko that's really odd, I'll raise it with Kubecost Engineering.

**Comment by liorfranko** [comment] 2023-11-13 05:59
@mattray @cliffcolvin any update?

**Comment by andehpants** [comment] 2023-11-15 05:42
I have the same thing happening to me on clusters in `ap-southeast-2` and `eu-central-1`. The screenshot below are two nodes of the same `instance_type`. Also no integration with CUR and spot-data feed.
 
![image](https://github.com/opencost/opencost/assets/84946994/4f24dd30-66db-403d-8d09-a46f6d00222d)

**Comment by thomasvn** [comment] 2023-11-21 03:35
@liorfranko Thanks for the detailed writeup + screenshots! Looking at this now.

Could you provide some additional screenshots on what `node_cpu_hourly_cost` and `node_ram_hourly_cost` look like on an accurate `c5d.18xlarge` versus an inaccurate `c5d.18xlarge` node? I'd like to narrow down where the issue is since those two values are how `node_total_hourly_cost` is calculated:

https://github.com/opencost/opencost/blob/418feea2890ca3a617ba8e33623aae7878b01c76/pkg/costmodel/metrics.go#L514

**Comment by liorfranko** [comment] 2023-11-21 21:33
Sure.
<img width="1632" alt="Screen Shot 2023-11-21 at 23 32 06" src="https://github.com/opencost/opencost/assets/20726865/82f5d4c5-8ca4-4be3-842a-396dfc3a0aae">

<img width="1633" alt="Screen Shot 2023-11-21 at 23 27 26" src="https://github.com/opencost/opencost/assets/20726865/6ff52c51-0a78-48f9-8668-3a7f3ba75f83">
<img width="1636" alt="Screen Shot 2023-11-21 at 23 27 07" src="https://github.com/opencost/opencost/assets/20726865/71fa4e54-f908-4ea3-97a9-f94ab20125af">
<img width="1629" alt="Screen Shot 2023-11-21 at 23 24 08" src="https://github.com/opencost/opencost/assets/20726865/90b195f8-adf3-4a65-9269-2f764c524958">

So the question is how `node_cpu_hourly_cost` and `node_ram_hourly_cost` are calculated.

**Comment by liorfranko** [comment] 2023-11-21 21:53
Both nodes has the same `kube_node_status_capacity_cpu_cores`, `kube_node_status_capacity_memory_bytes`, `kube_node_status_allocatable_memory_bytes` and `kube_node_status_allocatable_cpu_cores`.
<img width="1641" alt="Screen Shot 2023-11-21 at 23 52 17" src="https://github.com/opencost/opencost/assets/20726865/36882af1-f5bc-42da-af8a-ceb263b54340">

**Comment by thomasvn** [comment] 2023-11-27 22:53
@liorfranko I investigated this a bit further. The following code block is where we are emitting values for `node_cpu_hourly_cost` and `node_ram_hourly_cost`.

https://github.com/opencost/opencost/blob/418feea2890ca3a617ba8e33623aae7878b01c76/pkg/costmodel/metrics.go#L534-L558

I suspect that we may be observing outliers when querying the k8s api as detailed here https://github.com/opencost/opencost/issues/927. We may need to re-look at how we're performing outlier detection.

**Comment by thomasvn** [comment] 2023-11-29 23:27
@liorfranko Still looking into this, but could you provide the following info so we can further troubleshoot:

- Logs from the Opencost container which is emitting the incorrect `node_total_hourly_cost`
- Screenshots from Grafana or Prometheus of `kube_node_status_allocatable_cpu_cores` and `kube_node_status_capacity_memory_bytes / 1024 / 1024 / 1024` for the node which is emitting incorrect `node_total_hourly_cost` (example below)

![Screenshot 2023-11-29 at 3 25 01 PM](https://github.com/opencost/opencost/assets/11251627/c3885904-83ab-4af9-8a7a-c24bbc5a3d34)

![Screenshot 2023-11-29 at 3 25 17 PM](https://github.com/opencost/opencost/assets/11251627/3178f69f-180f-47a2-bb3c-a0241c41ed21)

**Comment by liorfranko** [comment] 2023-12-05 20:33
<img width="1646" alt="Screen Shot 2023-12-05 at 22 32 47" src="https://github.com/opencost/opencost/assets/20726865/02ca2b46-c37a-407d-b602-73ebafedf2b9">
<img width="1645" alt="Screen Shot 2023-12-05 at 22 32 28" src="https://github.com/opencost/opencost/assets/20726865/d03445a5-be7e-4b90-b7b3-9727bd12860f">

And I do see many 'outlier detected' logs:
```
2023-12-05T20:06:35.669815581Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669852271Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.669862292Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669874182Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.669882622Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669895282Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.669904942Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669926082Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.669935873Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669946133Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.669955883Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669966633Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.669974853Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.669998144Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670006664Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670017114Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670025354Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670036774Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670044855Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670064105Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670073575Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670084405Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670093095Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670104836Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670128006Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670147786Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670156336Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670166857Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670175787Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670186567Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670195747Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670208457Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670231288Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670246638Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670252258Z WRN RAM cost outlier detected; skipping data point.
2023-12-05T20:06:35.670280859Z WRN CPU cost outlier detected; skipping data point.
2023-12-05T20:06:35.670290579Z WRN RAM cost outlier detected; skipping data point.
```

**Comment by sachin-rafay** [comment] 2023-12-12 17:07
Hi All, I also faced the same issue.
According to my analysis, this issue happens when the cluster has nodes which are spot instances. The code picks the  hardcoded default spot cpu cost as the CPU cost and doesn't pick any RAM cost. 
https://github.com/opencost/opencost/blob/develop/pkg/cloud/aws/provider.go#L1308-L1320

I have a fix for it. Here is the PR: https://github.com/opencost/opencost/pull/2386

**Comment by thomasvn** [comment] 2023-12-13 00:15
@sachin-rafay Thanks for investigating and proposing a PR here!

@liorfranko Does this align with what you're seeing? Is the `node_total_hourly_cost` primarily occurring for spot nodes? For reference, I think this is the default value for `spotCPU`:

https://github.com/opencost/opencost/blob/40ab230587d3c2cf530ae3a8d0c374e4122702c3/configs/aws.json#L5

**Comment by liorfranko** [comment] 2023-12-14 17:15
I don't think it's my case, we do use Spots, but if it would have been the case I wouldn't have seen the same instance type in the same AZ with two different prices, and I would have seen the log `"marked preemptible but we have no data in spot feed"`

**Comment by sachin-rafay** [comment] 2023-12-14 17:25
Thank you for your response @liorfranko!
Two clarifying questions, 
1. Were both instances spot instances but showed different prices?
2. Did you check logs from the start in your inaccurate node? I am asking because, you will only see that log 5 times only when opencost starts. Then that log gets suppressed.

**Comment by liorfranko** [comment] 2023-12-18 19:28
Hi @sachin-rafay 
1. Were both instances spot instances but showed different prices? - yes.
2. Did you check logs from the start in your inaccurate node? yes, it happens all the time and I went over the logs a couple of times.
I do see the `CPU cost outlier detected; skipping data point` logs constantly.

**Comment by thomasvn** [comment] 2023-12-19 17:42
@liorfranko Did you see any occurrences of this log line?

https://github.com/opencost/opencost/blob/c38dbed76e070a4119186e7d4b7e9999033daecd/pkg/cloud/aws/provider.go#L1309

**Comment by abirsigron** [comment] 2023-12-26 09:39
Hey @thomasvn I am from @liorfranko team. 
We do see this warning logs:
```
2023-12-26T09:35:28.959757494Z WRN Node i-xxx marked preemptible but we have no data in spot feed
2023-12-26T09:35:28.959835048Z WRN Node i-xxx marked preemptible but we have no data in spot feed
2023-12-26T09:35:28.96000371Z WRN Node i-xxx marked preemptible but we have no data in spot feed
2023-12-26T09:35:28.960152804Z WRN Node i-xxx marked preemptible but we have no data in spot feed
2023-12-26T09:35:28.960159406Z INF Node %s marked preemptible but we have no data in spot feed logged 5 times: suppressing future logs
```

**Comment by liorfranko** [comment] 2023-12-27 07:14
I've checked the PR: https://github.com/opencost/opencost/pull/2386 on multiple instance types and it does solve the issue.

Thanks @sachin-rafay

**Comment by raghavendra-rafay** [comment] 2023-12-27 07:21
Thanks @sachin-rafay for the fix. This is helpful for our spot environment.

**Comment by kohbis** [comment] 2024-02-01 13:53
Do you have plans to release this change?
https://github.com/opencost/opencost/pull/2386#issuecomment-1884067792

**Comment by dwbrown2** [comment] 2024-02-01 14:13
@kohbis #2386 is now merged. @cliffcolvin @AjayTripathy would that be in 2.0 release?

**Comment by mattray** [comment] 2024-02-05 06:19
If this is in Kubecost 2.0 it should be in the release this week of OpenCost.

**Comment by thomasvn** [comment] 2024-05-22 18:00
Resolved by https://github.com/opencost/opencost/pull/2386

**Closed as completed by thomasvn** 2024-05-22 18:00 UTC
Labels: opencost, P1, kubecost, E2, needs-follow-up
