### ISSUE TITLE
document AWS_CLUSTER_ID

### ISSUE THREAD

**Issue by trondhindenes** [opencost/opencost#1808] opened 2023-03-25 10:11 UTC
**Describe the bug**
In my logs I can see `Unable to sniff out cluster ID, perhaps set $AWS_CLUSTER_ID to force one`. There's no mention of this environment variable in the documentation. It would be good if it was documented

**To Reproduce**
Install opencost with quickstart, see opencost pod output

**Expected behavior**

**Screenshots**

**Which version of OpenCost are you using?**
`quay.io/kubecost1/kubecost-cost-model:latest`

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by mattray** [comment] 2023-03-27 05:54
Duplicate of https://github.com/opencost/opencost/issues/1753

**Closed as completed by mattray** 2023-03-27 05:54 UTC
Labels: needs-triage
